version: '3'

services:
  jenkins:
    container_name: jenkins
    build: ./jenkins
    ports:
      - '8080:8080'
      - '443:8443'
      - '50000:50000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins_home:/var/jenkins_home
  
  git-server:
    build:
      dockerfile: gitserver.Dockerfile
      context: .
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./repos:/var/www/git
  
  webapp:    
    image: php:7.2-apache
    container_name: webapp
    volumes:
      - "./src:/var/www/html"
    ports:
      - "80:80"
    
  # SonarQube service
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube2
    ports:
      - "9000:9000"
    environment:
      SONARQUBE_JDBC_USERNAME: admin
      SONARQUBE_JDBC_PASSWORD: 2200648
    volumes:
      - "C:\Users\Joseph Lim\Desktop\SIT Stuff\ICT2216 SSD\Lab Test\Main\Question\sonarqube_data:/opt/sonarqube/data"
     
volumes:
  jenkins_data:
    driver: local